parameters:
    security.acl.mask_builder: ~

services:
    acl.tree.reader:
        class: GoDisco\AclTreeBundle\Annotation\AclParentReader
        arguments: ["@doctrine","@annotation_reader","@property_accessor"]

    security.acl.user_permission.map:
        class: %security.acl.permission.map.class%

    acl.tree.voter:
        class:      GoDisco\AclTreeBundle\Security\Authorization\Voter\AclTreeVoter
        public:     false
        arguments: ["@security.acl.provider","@security.acl.object_identity_retrieval_strategy","@security.acl.security_identity_retrieval_strategy","@security.acl.user_permission.map","@logger", true,"@doctrine","@acl.tree.reader"]
        tags:
           - { name: security.voter }

    acl.tree.helper:
        class: GoDisco\AclTreeBundle\Security\Helper\AclTreeHelper
        arguments: ["@doctrine.orm.entity_manager","@security.token_storage","@acl.tree.reader","@security.acl.dbal.connection","%security.acl.mask_builder%"]

    acl.object.users:
        class: GoDisco\AclTreeBundle\Security\Helper\AclUsersHelper
        arguments: ["@doctrine.orm.entity_manager","@property_accessor","@security.acl.dbal.connection","%security.acl.mask_builder%"]
